"""Measured error rates shipped with the code (generated by scripts/eval_analytics.py)."""

import json
from pathlib import Path

PATH = Path(__file__).with_name("error_rates.json")

NOT_MEASURED = {
    "label": "not measured",
    "note": "No error-rate file is installed; run scripts/eval_analytics.py. Treat as unknown.",
    "configs": [],
}


def load() -> dict:
    try:
        return json.loads(PATH.read_text())
    except (OSError, ValueError):
        return {"entries": {}}


def for_kind(kind: str, params: dict | None = None) -> dict:
    """Error-rate record for a model/config, with a flag saying whether the run's confidence
    threshold equals one that was actually measured."""
    entry = dict(load().get("entries", {}).get(kind) or NOT_MEASURED)
    entry["generated_by"] = load().get("generated_by", "")
    thr = (params or {}).get("conf_threshold")
    measured = {c.get("confidence_threshold") for c in entry.get("configs", [])}
    entry["run_threshold_measured"] = thr in measured if thr is not None else None
    return entry
