"""Validation harness: runs the scenario matrix on SYNTHETIC images and writes JSON + Markdown.

    python -m app.validation.run --seed 20260101 --trials 20 --out ../docs/validation

Synthetic scores demonstrate that the pipeline works on the layouts we modelled; they do not
predict performance on real devices. A parser built from a paper's layout and tested on images
generated from the same layout is a circular check, not independent validation.
"""

import argparse
import hashlib
import io
import json
import random
import sys
import tempfile
import time
from dataclasses import asdict
from pathlib import Path

from app import __version__
from app.carving import nal
from app.carving.carve import CarveParams, Carver
from app.carving.carve import Clip as CarvedClip
from app.carving.export import export_clip
from app.validation import thresholds
from app.validation.scenarios import SCENARIOS, Scenario
from app.validation.score import Carved, Counts, rate, score_image
from app.validation.streams import VARIANTS, StreamPool

DISCLAIMER = [
    "SYNTHETIC: every image in this report was generated by Nirikshan's validation harness. "
    "Scores show that the pipeline behaves as designed on the layouts we modelled; they do NOT "
    "predict performance on real DVR/NVR images.",
    "Parsers built from a paper's layout and tested on images generated from the same layout "
    "are a circular check, not independent validation. Layout variants are labeled 'per-paper "
    "layout, not a real device image'.",
    "No vendor is Tier A (validated on real images with ground truth we created).",
]


def trial_rng(seed: int, scenario: Scenario, trial: int) -> random.Random:
    key = f"{seed}|{scenario.group or scenario.id}|{trial}".encode()
    return random.Random(int.from_bytes(hashlib.sha256(key).digest()[:8], "big"))


def build_trial(sc: Scenario, pool: StreamPool, seed: int, trial: int):
    b = sc.build(trial_rng(seed, sc, trial), pool, trial)
    return b.build()


def run_generic(
    img: bytes, params: CarveParams, export: bool, tmp: Path
) -> tuple[list[Carved], dict, list]:
    def read_at(o, n):
        return img[o : o + n]

    carver = Carver(read_at, params)
    out: list[Carved] = []
    f = io.BytesIO(img)
    for k, item in enumerate(carver.run(nal.scan(f, len(img)))):
        if not isinstance(item, CarvedClip):
            continue
        cl = Carved(item.codec, [list(e) for e in item.extents], item.reassembled)
        if export:
            res = export_clip(f, item.extents, item.codec, tmp, f"c{k}")
            cl.decode_status, cl.recorded_sha256 = res.decode_status, res.bitstream_sha256
            if res.mp4_path:
                cl.mp4_ok = (
                    hashlib.sha256(Path(res.mp4_path).read_bytes()).hexdigest() == res.mp4_sha256
                )
        out.append(cl)
    return out, carver.stats, carver.join_log


ENGINES = {"generic": run_generic}


def run_scenario(
    sc: Scenario, pool: StreamPool, seed: int, trials: int, engine: str, export: bool
) -> dict:
    n = sc.trials or trials
    total = Counts()
    t0 = time.perf_counter()
    for i in range(n):
        img, truth = build_trial(sc, pool, seed, i)
        params = CarveParams(**sc.carve)
        with tempfile.TemporaryDirectory() as tmp:
            carved, _stats, joins = ENGINES[engine](img, params, export and sc.export, Path(tmp))
            total.add(score_image(truth, carved, img, f"{sc.id}#{i}", joins))
    c = total
    if sc.kind == "positive":
        metrics = {
            "clip_recall": rate(c.truth_detected, c.truth_expected),
            "clip_precision": rate(c.tp, c.carved),
            "byte_exact": rate(c.exact, c.exact_eligible),
            "frame_recall": rate(c.frames_recovered, c.frames_recoverable),
            "frame_precision": rate(c.frames_recovered, c.frames_covered_any),
            "decode_ok": rate(c.decode_ok, c.carved) if export and sc.export else None,
            "hash_integrity": rate(c.hash_ok, c.hash_checked) if c.hash_checked else None,
            "mixed_clips": rate(c.mixed, c.carved),
        }
        if c.join_wrong_candidates + c.join_right_candidates:
            metrics["reassembler_false_accept"] = rate(
                c.join_wrong_accepted, c.join_wrong_candidates
            )
            metrics["reassembler_true_accept"] = rate(
                c.join_right_accepted, c.join_right_candidates
            )
    else:
        metrics = {
            "clips_emitted": {"k": c.neg_clips, "n": c.images},
            "clips_decoded_ok": {"k": c.neg_decode_ok, "n": c.images},
            "emitted_but_flagged_failed": {"k": c.decode_errors + c.export_failed, "n": c.images},
        }
    return {
        "id": sc.id,
        "title": sc.title,
        "kind": sc.kind,
        "description": sc.description,
        "carve_params": sc.carve,
        "trials": n,
        "layout": "raw: generic elementary-stream placement (no vendor structures)",
        "counts": {k: v for k, v in asdict(c).items() if k != "failures"},
        "metrics": metrics,
        "failures": c.failures[:8],
        "failure_count": len(c.failures),
        "seconds": round(time.perf_counter() - t0, 2),
    }


def run_all(seed: int, trials: int, engine="generic", export=True, only=None) -> dict:
    pool = StreamPool()
    scs = [s for s in SCENARIOS if not only or s.id in only]
    res = {
        "synthetic": True,
        "disclaimer": DISCLAIMER,
        "tool_version": __version__,
        "ffmpeg": pool.ffmpeg,
        "engine": engine,
        "seed": seed,
        "trials": trials,
        "export_decode_test": export,
        "scenarios": [run_scenario(s, pool, seed, trials, engine, export) for s in scs],
    }
    res["stream_pool"] = [
        {"name": s.variant.name, "sha256": hashlib.sha256(s.data).hexdigest(), "frames": s.frames}
        for s in pool.all()
    ]
    res["results_digest"] = digest(res)
    return res


def digest(res: dict) -> str:
    """Hash of everything except wall-clock timings and the digest itself."""
    d = json.loads(json.dumps(res))
    d.pop("results_digest", None)
    d.pop("thresholds", None)  # derived afterwards from the metrics
    for s in d["scenarios"]:
        s.pop("seconds", None)
    return hashlib.sha256(json.dumps(d, sort_keys=True).encode()).hexdigest()


def pct(m: dict | None) -> str:
    if not m or m.get("rate") is None:
        return "n/a"
    lo, hi = m["ci95"]
    return f"{m['rate'] * 100:.1f}% ({m['k']}/{m['n']}) [{lo * 100:.0f}-{hi * 100:.0f}]"


def to_markdown(res: dict) -> str:
    L = ["# Nirikshan validation results (SYNTHETIC)", ""]
    L += [f"> **{d}**" for d in res["disclaimer"][:2]] + [""]
    L += [
        f"- {res['disclaimer'][2]}",
        f"- Seed {res['seed']}, {res['trials']} trials per scenario, engine `{res['engine']}`, "
        f"tool {res['tool_version']}, {res['ffmpeg']}.",
        f"- Results digest `{res['results_digest']}` (excludes timings).",
        "",
    ]
    L += [
        "Rates are k/n with a Wilson 95% interval in brackets. 'Frame' means a VCL NAL unit lying inside carved "
        "extents (not a decoder output). 'Recoverable' frames are those whose own bytes and their GOP's prefix and parameter sets survived.",
        "",
    ]
    pos = [s for s in res["scenarios"] if s["kind"] == "positive"]
    L += [
        "## Positive scenarios",
        "",
        "| Scenario | Trials | Clip recall | Clip precision | Byte-exact | Frame recall | Frame precision | Decode ok | Hash integrity |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for s in pos:
        m = s["metrics"]
        L.append(
            f"| `{s['id']}` | {s['trials']} | {pct(m['clip_recall'])} | {pct(m['clip_precision'])} | {pct(m['byte_exact'])} | {pct(m['frame_recall'])} | {pct(m['frame_precision'])} | {pct(m['decode_ok'])} | {pct(m['hash_integrity'])} |"
        )
    fa = [s for s in pos if "reassembler_false_accept" in s["metrics"]]
    if fa:
        L += [
            "",
            "## Fragment reassembler (H.264 only)",
            "",
            "| Scenario | False-accept (wrong joins accepted / wrong candidates) | True-accept (correct joins accepted / correct candidates) |",
            "|---|---|---|",
        ]
        for s in fa:
            m = s["metrics"]
            L.append(
                f"| `{s['id']}` | {pct(m['reassembler_false_accept'])} | {pct(m['reassembler_true_accept'])} |"
            )
    neg = [s for s in res["scenarios"] if s["kind"] == "negative"]
    L += [
        "",
        "## Negative scenarios (no decodable clip may be produced)",
        "",
        "| Scenario | Images | Clips emitted | Clips decoding OK (must be 0) | Emitted but flagged failed |",
        "|---|---|---|---|---|",
    ]
    for s in neg:
        m = s["metrics"]
        L.append(
            f"| `{s['id']}` | {s['trials']} | {m['clips_emitted']['k']} | {m['clips_decoded_ok']['k']} | {m['emitted_but_flagged_failed']['k']} |"
        )
    L += ["", "## Scenario descriptions", ""]
    L += [f"- `{s['id']}`: {s['description']}" for s in res["scenarios"]]
    L += ["", "## Failure examples (first per scenario)", ""]
    for s in res["scenarios"]:
        if s["failures"]:
            L.append(
                f"- `{s['id']}` ({s['failure_count']} total): `{json.dumps(s['failures'][0])}`"
            )
    L += [
        "",
        "## Stream pool (SYNTHETIC testsrc2 encodes)",
        "",
        "| Variant | Frames | SHA-256 |",
        "|---|---|---|",
    ]
    L += [f"| {p['name']} | {p['frames']} | `{p['sha256'][:16]}…` |" for p in res["stream_pool"]]
    t = res.get("thresholds")
    if t:
        L += [
            "",
            f"Regression thresholds ({t['file']}): "
            + ("PASS" if not t["violations"] else "FAIL: " + "; ".join(t["violations"])),
        ]
    L += ["", f"Variants defined: {', '.join(v.name for v in VARIANTS)}."]
    return "\n".join(L) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="validate")
    ap.add_argument("--seed", type=int, default=20260101)
    ap.add_argument("--trials", type=int, default=20)
    ap.add_argument("--engine", default="generic", choices=sorted(ENGINES))
    ap.add_argument("--out", default="")
    ap.add_argument(
        "--no-export", action="store_true", help="skip ffmpeg export/decode test (faster)"
    )
    ap.add_argument("--only", nargs="*", help="scenario ids")
    ap.add_argument("--check", action="store_true", help="exit 1 if regression thresholds fail")
    a = ap.parse_args(argv)
    res = run_all(a.seed, a.trials, a.engine, not a.no_export, set(a.only) if a.only else None)
    viol = thresholds.check(res)
    res["thresholds"] = {"file": "app/validation/thresholds.json", "violations": viol}
    md = to_markdown(res)
    print(md)
    print("Regression thresholds:", "PASS" if not viol else f"FAIL {viol}")
    if a.out:
        out = Path(a.out)
        out.mkdir(parents=True, exist_ok=True)
        (out / "results.json").write_text(json.dumps(res, indent=1, sort_keys=True) + "\n")
        (out / "results.md").write_text(md)
    return 1 if (a.check and viol) else 0


if __name__ == "__main__":
    sys.exit(main())
